// AUTO-GENERATED by scripts/gen-frames-enum.mjs from src/content/_zoom.yaml
// Do not hand-edit. Run `node scripts/gen-frames-enum.mjs` (or pnpm build) to regenerate.
export const FRAMES = ['cost', 'diy', 'proof', 'risk', 'timing', 'fit'] as const;
export type FrameId = (typeof FRAMES)[number];
